### PR TITLE
Feature/url shortening

### PR DESCRIPTION
**Pull request by andrewmiko**
This PR covers URL shortening function using SHA1 mechanism.

This PR also includes #11 because it's depends on Url model.

### CODE REVIEW

**Review by aryan9600 — APPROVED** [review]
LGTM! @ShubhamPalriwala could you take a look as well?

**Comment by ShubhamPalriwala** [comment]
@andrewmiko It logs out this error when I try to shorten the URL through `localhost:5000/api/shorten/url` with the body as:
`{"url":"website.com"}`
```
127.0.0.1 - - [03/Oct/2020 04:06:48] "←[37mPOST /api/shorten/quick HTTP/1.1←[0m" 200 -
(sqlite3.OperationalError) no such table: url
[SQL: SELECT url.id AS url_id, url.original_url AS url_original_url, url.short_url AS url_short_url
FROM url
WHERE url.original_url = ?
 LIMIT ? OFFSET ?]
[parameters: ('website.com', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by andrewmiko** [comment]
@ShubhamPalriwala I'll check later. There is `db_init` function in `app.py` which automatically should create database with all tables.

**Comment by andrewmiko** [comment]
@ShubhamPalriwala @aryan9600 issue fixed

**Comment by ShubhamPalriwala** [comment]
@andrewmiko is the shortened url redirecting you to the actual url ?
This time i do get a shortened url from the `/api/shorten/url` but it does not redirect me to the actual url !

**Comment by aryan9600** [comment]
@ShubhamPalriwala I don't think this PR is supposed to address that. Since we have a different route for the actual redirecting, we can have another issue/PR for that.
If the shortening of the URl works as expected, this LGTM!

**Pull request merged**
